// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxxfablfqigoewcfmjzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eGZhYmxmcWlnb2V3Y2ZtanpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjUzODcsImV4cCI6MjA3MDYwMTM4N30.KKHtm7Cx_1vba7KHC_GWy0UmKEezI7K7GyLeSR2-vio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});