// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqfmckhgjoojfuaovkbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZm1ja2hnam9vamZ1YW92a2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3ODExMjgsImV4cCI6MjA4OTM1NzEyOH0.LaRl3KMmWfynIFFTcF3yizXNshU8HBJDy8xzGC8_0MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});